### ISSUE TITLE
compatibility with django-tables2 > 2.0

### ISSUE THREAD

**Issue by simpuc** [goinnn/django-tables2-reports#44]
Hello,
could you please modify tables.py as follow:

```
88,89c88,89
<         if not 'template' in kwargs:
<             kwargs['template'] = 'django_tables2_reports/table.html'
---
>         if not 'template_name' in kwargs:
>             kwargs['template_name'] = 'django_tables2_reports/table.html'
```
It is needed to have compatibility with django-tables2 >2.0

Thank you

Simone

**Comment by mpasternak** [comment]
Hi, maintainer here, 

how about compatibility with older django-tables2 versions, how could you check for that? Maybe it would be better to check for both ``template`` and ``template_name``, how do you think? 

Any chances of creating a test for this bug? 

Also... django-tables2-reports is retired. As it says in the  README, please feel free to explore other options of django-tables2, because django-tables2 has means to export stuff using tablib. I did that for my project, learning curve is not as steep, check it out, it's very cool. 

If you want me to submit your patch, think about compatibility with older versions, add a unit test and reopen. Thanks.

**Comment by simpuc** [comment]
Hi Michal,
thank you for your answer. I will use django-tables2  and tablib
ATB
Simone

**Comment by mpasternak** [comment]
It will take a while to convert but you’ll be better right after. Also, less code to support. Thanks for understanding
